on:
  push:
    paths:
      - 'data-raw/CreateInterractiveItemsForCorrections.R'
    branches:
      - master
  pull_request:
    paths:
      - 'data-raw/CreateInterractiveItemsForCorrections.R'
    branches:
      - master

name: Update Correrction Functions interactive items

jobs:
  create_interactive_items_CorrerctionFunctions:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
# - name: Install dependancies
#
# run: |
#   install.packages(c("remotes", "rcmdcheck"))
# remotes::install_deps(dependencies = TRUE)
# shell: Rscript {0}

      - name:  Create interactive_items_CorrerctionFunctions
        run: |
          source('data-raw/CreateInterractiveItemsForCorrections.R')
        shell: Rscript {0}

      - name: Commit new files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add --all
          git commit -am "update interactive_items_CorrerctionFunctions.csv"
          git push
