
library(shinytest)
#  viewTestDiff("inst/app/", "ForestGeotoForestPlot_test")
#  snapshotUpdate("inst/app/", "ForestGeotoForestPlot_test")


app <- ShinyDriver$new("../../")
app$snapshotInit("ForestGeotoForestPlot_test")

app$setInputs(nTable = 2)
app$setInputs(nTable = 4)
app$uploadFile(file1 = "scbi.stem1.csv")
app$uploadFile(file2 = "scbi.stem2.csv")
app$uploadFile(file3 = "scbi.stem3.csv")
app$uploadFile(file4 = "scbi.spptable.csv")
app$setInputs(submitTables = "click")
app$setInputs(TablesToStack = "Table1")
app$setInputs(TablesToStack = c("Table1", "Table2"))
app$setInputs(TablesToStack = c("Table1", "Table2", "Table3"))
app$setInputs(Stack = "click")
app$setInputs(GoToMerge = "click")
app$setInputs(leftTable = "StackedTables")
app$setInputs(rightTable = "Table4")
app$setInputs(selectLeft = "click")
app$setInputs(selectRight = "click")
app$setInputs(leftKey = "sp")
app$setInputs(rightKey = "sp")
app$setInputs(Merge = "click")
app$setInputs(GoToTidy = "click")
app$setInputs(SkipTidy = "click")
app$uploadFile(profile = "ForestGeoProfile.rds")
app$setInputs(UseProfile = "click")
app$setInputs(UseProfile = "click")
app$setInputs(LaunchFormating = "click")
app$setInputs(GoToCorrect = "click")
app$setInputs(SkipCorrections = "click")
app$uploadFile(profileOutput = "ForestPlots_test2_trees_small_Profile.rds")
app$setInputs(UseProfileOutput = "click")
app$snapshot()
