
library(shinytest)
#  viewTestDiff("inst/app/", "ForestPlotToForestGeo_test")
#  snapshotUpdate("inst/app/", "ForestPlotToForestGeo_test")


app <- ShinyDriver$new("../../")
app$snapshotInit("ForestPlotToForestGeo_test")

app$setInputs(nTable = 2)
app$uploadFile(file1 = "ForestPlots_test2_trees_small.csv")
app$uploadFile(file2 = "ForestPlots_test2_plots_small.csv")
app$setInputs(submitTables = "click")
app$setInputs(SkipStack = "click")
app$setInputs(leftTable = "Table1")
app$setInputs(rightTable = "Table2")
app$setInputs(selectLeft = "click")
app$setInputs(selectRight = "click")
app$setInputs(leftKey = "PlotID")
app$setInputs(rightKey = "Plot ID")
app$setInputs(Merge = "click")
app$setInputs(GoToTidy = "click")
app$setInputs(SkipTidy = "click")
app$uploadFile(profile = "ForestPlots_test2_trees_small_Profile.rds")
app$setInputs(UseProfile = "click")
app$setInputs(UseProfile = "click")
app$setInputs(LaunchFormating = "click")
app$setInputs(GoToCorrect = "click")
app$setInputs(SkipCorrections = "click")
app$uploadFile(profileOutput = "ForestGeoProfile.rds") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(UseProfileOutput = "click")
app$snapshot()
app$snapshotDownload("dbMetadata")
app$snapshotDownload("dbFile")
# app$snapshotDownload("dbCode")
