library(shinytest)
#  viewTestDiff("inst/app/", "SCBI_ForestGeo_test")
#  snapshotUpdate("inst/app/", "SCBI_ForestGeo_test")


app <- ShinyDriver$new("../../")
app$snapshotInit("SCBI_ForestGeo_test")

app$setInputs(nTable = 2)
app$setInputs(nTable = 3)
app$setInputs(nTable = 4)
app$uploadFile(file1 = "scbi.stem1.csv")
app$uploadFile(file2 = "scbi.stem2.csv")
app$uploadFile(file3 = "scbi.stem3.csv")
app$uploadFile(file4 = "scbi.spptable.csv")
app$setInputs(submitTables = "click")
app$setInputs(TablesToStack = "Table1")
app$setInputs(TablesToStack = c("Table1", "Table2"))
app$setInputs(TablesToStack = c("Table1", "Table2", "Table3"))
app$setInputs(Stack = "click")
app$setInputs(GoToMerge = "click")
app$setInputs(leftTable = "StackedTables")
app$setInputs(selectLeft = "click")
app$setInputs(leftKey = "sp")
app$setInputs(rightTable = "Table4")
app$setInputs(selectRight = "click")
app$setInputs(rightKey = "sp")
app$setInputs(Merge = "click")
app$setInputs(GoToTidy = "click")
app$setInputs(SkipTidy = "click")
app$uploadFile(profile = "ForestGeoProfile.rds")
app$setInputs(UseProfile = "click")
app$setInputs(UseProfile = "click")
app$setInputs(tabs = "Tidying")
app$setInputs(tabs = "Merging")
app$setInputs(tabs = "Headers")
app$setInputs(LaunchFormating = "click")
app$setInputs(GoToCorrect = "click")
app$setInputs(SkipCorrections = "click")
app$setInputs(DontUseProfileOutput = "click")
app$snapshotDownload("dbFile")
# app$snapshotDownload("dbCode")
app$snapshotDownload("dbMetadata")
app$snapshot()
