#' ParacouProfile
#'
#' Generated by interacting with app or function RequiredFormat_interactive
#' @format A named list
#' \describe{
#'   \item{TreeHeight}{Value or column name in data set @ParacouSubset (none) corresponding to Tree height}
#'   \item{XTreeUTM}{Value or column name in data set @ParacouSubset (none) corresponding to Tree X UTM coordinate}
#'   \item{Date}{Value or column name in data set @ParacouSubset (CensusDate) corresponding to Date of measurement}
#'   \item{SubplotAreaMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is your Subplot area in hectare?}
#'   \item{SpeciesVolume}{Value or column name in data set @ParacouSubset (none) corresponding to Species volume}
#'   \item{POM}{Value or column name in data set @ParacouSubset (none) corresponding to POM}
#'   \item{PlotAreaUnitMan}{Value or column name in data set @ParacouSubset (ha) corresponding to What is the unit for plot area?}
#'   \item{BHOMUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your BasalHOM unit?}
#'   \item{PlotVolume}{Value or column name in data set @ParacouSubset (none) corresponding to Plot volume}
#'   \item{BD}{Value or column name in data set @ParacouSubset (none) corresponding to BD}
#'   \item{PlotDensity}{Value or column name in data set @ParacouSubset (none) corresponding to Tree Density}
#'   \item{IdStem}{Value or column name in data set @ParacouSubset (none) corresponding to Stem ID}
#'   \item{YTreeSubplot}{Value or column name in data set @ParacouSubset (none) corresponding to Tree Y euclidean position in SUBplot}
#'   \item{PlotMan}{Value or column name in data set @ParacouSubset () corresponding to What is your plot name ?}
#'   \item{YPlotUTM}{Value or column name in data set @ParacouSubset (none) corresponding to Plot Y UTM coordinate}
#'   \item{IdMeasure}{Value or column name in data set @ParacouSubset (none) corresponding to Measure ID}
#'   \item{ScientificName}{Value or column name in data set @ParacouSubset (none) corresponding to Scientific name}
#'   \item{SpeciesBasalAreaDensityUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your species basal area unit?}
#'   \item{SubplotArea}{Value or column name in data set @ParacouSubset (none) corresponding to Subplot area}
#'   \item{IdCensus}{Value or column name in data set @ParacouSubset (none) corresponding to Census ID}
#'   \item{XTreePlot}{Value or column name in data set @ParacouSubset (none) corresponding to Tree X euclidean position in plot}
#'   \item{PlotAreaMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is your plot area in hectare?}
#'   \item{PlotElevation}{Value or column name in data set @ParacouSubset (none) corresponding to Plot elevation}
#'   \item{BPOM}{Value or column name in data set @ParacouSubset (none) corresponding to Basal POM}
#'   \item{SpeciesDensityUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your species density unit?}
#'   \item{CommercialSp}{Value or column name in data set @ParacouSubset (CommercialSp) corresponding to Commercial species indicator}
#'   \item{IsCommercialMan}{Value or column name in data set @ParacouSubset (TRUE) corresponding to Which of the following(s) indicate a commercial species?}
#'   \item{SpeciesBasalAreaDensity}{Value or column name in data set @ParacouSubset (none) corresponding to Species basal area density}
#'   \item{YearMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is your year of measurement?}
#'   \item{Subspecies}{Value or column name in data set @ParacouSubset (none) corresponding to Subspecies name}
#'   \item{Circ}{Value or column name in data set @ParacouSubset (Circ) corresponding to Circumference}
#'   \item{SpeciesTotalBasalAreaUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your basal area unit?}
#'   \item{PlotVolumeUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your plot volume unit?}
#'   \item{PlotNDead}{Value or column name in data set @ParacouSubset (none) corresponding to Number of dead trees in the sampling unit}
#'   \item{XTreeSubplot}{Value or column name in data set @ParacouSubset (none) corresponding to Tree X euclidean position in SUBplot}
#'   \item{Site}{Value or column name in data set @ParacouSubset (Forest) corresponding to Site name}
#'   \item{Cluster}{Value or column name in data set @ParacouSubset (none) corresponding to Cluster of plots}
#'   \item{MinDBH}{Value or column name in data set @ParacouSubset (none) corresponding to Minimum DBH}
#'   \item{Day}{Value or column name in data set @ParacouSubset (none) corresponding to Day of measurement}
#'   \item{TreeUTMUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to Tree UTM units}
#'   \item{PlotNLive}{Value or column name in data set @ParacouSubset (none) corresponding to Number of living trees in the sampling unit}
#'   \item{SpeciesVolumeUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your species volume unit?}
#'   \item{BHOM}{Value or column name in data set @ParacouSubset (none) corresponding to Basal HOM}
#'   \item{IdTree}{Value or column name in data set @ParacouSubset (idTree) corresponding to Individual ID}
#'   \item{LifeForm}{Value or column name in data set @ParacouSubset (none) corresponding to Life form}
#'   \item{TreeSubplotUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to Tree XY subplot coordinates units}
#'   \item{VernName}{Value or column name in data set @ParacouSubset (VernName) corresponding to Vernacular name}
#'   \item{PlotSpeciesRichness}{Value or column name in data set @ParacouSubset (none) corresponding to Number of species}
#'   \item{SiteMan}{Value or column name in data set @ParacouSubset () corresponding to What is your site name ?}
#'   \item{XSubplotUTM}{Value or column name in data set @ParacouSubset (none) corresponding to Subplot X UTM coordinate}
#'   \item{Authority}{Value or column name in data set @ParacouSubset (none) corresponding to  Taxonomic authority for the ID level}
#'   \item{BCirc}{Value or column name in data set @ParacouSubset (none) corresponding to Basal Circumference}
#'   \item{PlotBasalAreaDensity}{Value or column name in data set @ParacouSubset (none) corresponding to Plot basal area density}
#'   \item{TreePlotUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to Tree XY plot coordinates units}
#'   \item{Diameter}{Value or column name in data set @ParacouSubset (none) corresponding to DBH}
#'   \item{Month}{Value or column name in data set @ParacouSubset (none) corresponding to Month of measurement}
#'   \item{HOMUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your HOM unit?}
#'   \item{SpeciesTotalBasalArea}{Value or column name in data set @ParacouSubset (none) corresponding to Species total basal area}
#'   \item{TreeHeightUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your tree height unit?}
#'   \item{Variety}{Value or column name in data set @ParacouSubset (none) corresponding to Variety name}
#'   \item{Family}{Value or column name in data set @ParacouSubset (Family) corresponding to Family name}
#'   \item{HOM}{Value or column name in data set @ParacouSubset (none) corresponding to HOM}
#'   \item{ScientificNameSepMan}{Value or column name in data set @ParacouSubset () corresponding to Character separating Genus and Species in Scientific name}
#'   \item{BDUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your BD unit ?}
#'   \item{YSubplotUTM}{Value or column name in data set @ParacouSubset (none) corresponding to Subplot Y UTM coordinate}
#'   \item{SpeciesCoverageIndex}{Value or column name in data set @ParacouSubset (none) corresponding to Species Coverage Frequency}
#'   \item{DiameterUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your DBH unit ?}
#'   \item{PlotElevationMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is your plot elevation in meters above sea level?}
#'   \item{SubplotMan}{Value or column name in data set @ParacouSubset () corresponding to What is your Subplot name ?}
#'   \item{DateFormatMan}{Value or column name in data set @ParacouSubset (yyyy-mm-dd) corresponding to What is your date format?}
#'   \item{Species}{Value or column name in data set @ParacouSubset (Species) corresponding to Species name}
#'   \item{SpeciesRelativeDensity}{Value or column name in data set @ParacouSubset (none) corresponding to Species Relative Density}
#'   \item{CircUnitMan}{Value or column name in data set @ParacouSubset (cm) corresponding to What is your circumference unit?}
#'   \item{IdLevel}{Value or column name in data set @ParacouSubset (none) corresponding to Determination rank}
#'   \item{XPlotUTM}{Value or column name in data set @ParacouSubset (none) corresponding to Plot X UTM coordinate}
#'   \item{TreeFieldNum}{Value or column name in data set @ParacouSubset (TreeFieldNum) corresponding to Inidividual tag}
#'   \item{YTreeUTM}{Value or column name in data set @ParacouSubset (none) corresponding to Tree Y UTM coordinate}
#'   \item{TreeLon}{Value or column name in data set @ParacouSubset (none) corresponding to Tree longitude}
#'   \item{BCircUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your basal circumference unit?}
#'   \item{SubplotLon}{Value or column name in data set @ParacouSubset (none) corresponding to Subplot longitude}
#'   \item{Year}{Value or column name in data set @ParacouSubset (CensusYear) corresponding to Year of measurement}
#'   \item{LifeStatus}{Value or column name in data set @ParacouSubset (CodeAlive) corresponding to Life status}
#'   \item{MinDBHMan}{Value or column name in data set @ParacouSubset (-999) corresponding to What is the minimum diameter of trees included in your inventory?}
#'   \item{PlotArea}{Value or column name in data set @ParacouSubset (PlotArea) corresponding to Plot area}
#'   \item{PlotLon}{Value or column name in data set @ParacouSubset (none) corresponding to Plot longitude}
#'   \item{YTreePlot}{Value or column name in data set @ParacouSubset (none) corresponding to Tree Y euclidean position in plot}
#'   \item{SpeciesRelativeDominance}{Value or column name in data set @ParacouSubset (none) corresponding to Species Relative Dominance}
#'   \item{Subplot}{Value or column name in data set @ParacouSubset (SubPlot) corresponding to Subplot name}
#'   \item{MinDBHUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your unit for the column indicating the minimum DBH? If not provided, it will be calculated looking at your Diameter column}
#'   \item{PlotDensityUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your plot density unit?}
#'   \item{PlotBasalAreaDensityUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is your plot basal area unit?}
#'   \item{Plot}{Value or column name in data set @ParacouSubset (Plot) corresponding to Plot name}
#'   \item{SpeciesImportanceIndex}{Value or column name in data set @ParacouSubset (none) corresponding to Species Importance Index}
#'   \item{SubplotAreaUnitMan}{Value or column name in data set @ParacouSubset (none) corresponding to What is the unit for Subplot area?}
#'   \item{Voucher}{Value or column name in data set @ParacouSubset (none) corresponding to Voucher code}
#'   \item{TreeLat}{Value or column name in data set @ParacouSubset (none) corresponding to Tree latitude}
#'   \item{PlotLat}{Value or column name in data set @ParacouSubset (none) corresponding to Plot latitude}
#'   \item{StemFieldNum}{Value or column name in data set @ParacouSubset (none) corresponding to Stem tag}
#'   \item{Genus}{Value or column name in data set @ParacouSubset (Genus) corresponding to Genus name}
#'   \item{SpeciesAbundance}{Value or column name in data set @ParacouSubset (none) corresponding to Species abundance}
#'   \item{IsLiveMan}{Value or column name in data set @ParacouSubset (TRUE) corresponding to Which of your status(es) represent a LIVE tree?}
#'   \item{SubplotLat}{Value or column name in data set @ParacouSubset (none) corresponding to Subplot latitude}
#'   \item{SpeciesDensity}{Value or column name in data set @ParacouSubset (none) corresponding to Species density}
#'   \item{SpeciesRelativeFrequency}{Value or column name in data set @ParacouSubset (none) corresponding to Species Relative Frequency}
#'   \item{MeasLevel}{Some value created via interaction with the Shiny app}
#'   \item{Tidy}{Some value created via interaction with the Shiny app}
#'   \item{ClearValueName}{Some value created via interaction with the Shiny app}
#'   \item{TickedMelt3}{Some value created via interaction with the Shiny app}
#'   \item{Variablecolumns1}{Some value created via interaction with the Shiny app}
#'   \item{ValueName4}{Some value created via interaction with the Shiny app}
#'   \item{TickedMelt1}{Some value created via interaction with the Shiny app}
#'   \item{ValueName5}{Some value created via interaction with the Shiny app}
#'   \item{ValueName2}{Some value created via interaction with the Shiny app}
#'   \item{TickedMelt4}{Some value created via interaction with the Shiny app}
#'   \item{TickedMelt5}{Some value created via interaction with the Shiny app}
#'   \item{Variablecolumns3}{Some value created via interaction with the Shiny app}
#'   \item{ValueName3}{Some value created via interaction with the Shiny app}
#'   \item{TickedMelt2}{Some value created via interaction with the Shiny app}
#'   \item{Variablecolumns2}{Some value created via interaction with the Shiny app}
#'   \item{ValueName1}{Some value created via interaction with the Shiny app}
#'   \item{AllCodes}{Some value created via interaction with the Shiny app}
#'   ...
#' }

#'
"ParacouProfile"
